version: "3.8"

services:
  app:
    build:
      context: .
    container_name: api
    ports:
      - 5000:5000
    volumes:
      - ./:/app # compare file changes within the container
      - node_modules:/app/node_modules
    restart: unless-stopped
    env_file: .env

volumes:
  node_modules: # creating tom for node_modules
