version: "3.8"

services:
  app_dev:
    build:
      context: .
    image: backend_basics:dev
    container_name: backend_dev
    ports:
      - 5000:5000
    volumes:
      - ./:/app # compare file changes within the container
      - node_modules:/app/node_modules
    restart: unless-stopped
    env_file: .env
  app_prod:
    build:
      context: .
    image: backend_basics:prod
    container_name: backend_prod
    ports:
      - 5002:5000
    volumes:
      - ./:/app
    restart: unless-stopped
    env_file: .env

volumes:
  node_modules: # creating tom for node_modules
